[build]
  # The directory where your project files are located
  base = "JavaTRAX-3000"
  
  # The directory where the built files will be published from
  publish = "JavaTRAX-3000/dist"
  
  # The build command to run
  command = "npm ci && npm run build"

[build.environment]
  # Specify Node.js version
  NODE_VERSION = "18"
  
  # Optimize for production
  NODE_ENV = "production"

# Handle client-side routing (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Add security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"