[build]
  base = "JavaTRAX-3000"
  publish = "JavaTRAX-3000/dist"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18"

[build]
  command = "npm cache clean --force && npm ci && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"